export const CURRENCIES = [
  { value: "USD", label: "USD - United States Dollar" },
  { value: "EUR", label: "EUR - Euro" },
  { value: "JPY", label: "JPY - Japanese Yen" },
  { value: "GBP", label: "GBP - British Pound Sterling" },
  { value: "AUD", label: "AUD - Australian Dollar" },
  { value: "CAD", label: "CAD - Canadian Dollar" },
  { value: "CHF", label: "CHF - Swiss Franc" },
  { value: "CNY", label: "CNY - Chinese Yuan" },
  { value: "HKD", label: "HKD - Hong Kong Dollar" },
  { value: "NZD", label: "NZD - New Zealand Dollar" },
  { value: "SEK", label: "SEK - Swedish Krona" },
  { value: "KRW", label: "KRW - South Korean Won" },
  { value: "SGD", label: "SGD - Singapore Dollar" },
  { value: "NOK", label: "NOK - Norwegian Krone" },
  { value: "MXN", label: "MXN - Mexican Peso" },
  { value: "INR", label: "INR - Indian Rupee" },
  { value: "RUB", label: "RUB - Russian Ruble" },
  { value: "ZAR", label: "ZAR - South African Rand" },
  { value: "BRL", label: "BRL - Brazilian Real" },
  { value: "TWD", label: "TWD - New Taiwan Dollar" },
  { value: "DKK", label: "DKK - Danish Krone" },
  { value: "PLN", label: "PLN - Polish Złoty" },
  { value: "THB", label: "THB - Thai Baht" },
  { value: "IDR", label: "IDR - Indonesian Rupiah" },
  { value: "HUF", "label": "HUF - Hungarian Forint" },
  { value: "CZK", label: "CZK - Czech Koruna" },
  { value: "ILS", label: "ILS - Israeli New Shekel" },
  { value: "CLP", label: "CLP - Chilean Peso" },
  { value: "PHP", label: "PHP - Philippine Peso" },
  { value: "AED", label: "AED - UAE Dirham" },
  { value: "COP", label: "COP - Colombian Peso" },
  { value: "SAR", label: "SAR - Saudi Riyal" },
  { value: "MYR", label: "MYR - Malaysian Ringgit" },
  { value: "RON", label: "RON - Romanian Leu" },
  { value: "LKR", label: "LKR - Sri Lankan Rupee" },
];
